repos:
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa  # frozen: v1.29.0
    hooks:
      - id: zizmor
        args: [--fix, --persona=pedantic]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 5c3f3c61b143a94e9ab5d767ff4d0dc9d6801aa3  # frozen: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
