repos:
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: fa412071e4f5d44d44f9e365f4676f9df92456a2
  hooks:
  - id: zizmor
    args:
    - --fix
    - --persona=pedantic
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: 91ab4bf57e58b32adf1a122681f6ebe164d081c8
  hooks:
  - id: conventional-pre-commit
    stages:
    - commit-msg
